### PR TITLE
Minor report improvements

### LINKED ISSUE #216: Minor improvements on report
- [x]  Error groups for in-row errors should show the headers row.

    zc5iafr

- [x] Rows previewed don't show the correct rows (10, 100, 101, 102...) (see img above)
- [x] If we only show the first 10 errors we should display a message saying so.

### PR DESCRIPTION
**Pull request by roll**
- fixes #216
  - added headers to error group with context body
  - fixed rows order (row number was correct just wrongly ordered rows)
  - add button `show 10 more rows` when table is truncated

### CODE REVIEW

**Comment by roll** [comment]
@amercader 
please take a look

**Comment by amercader** [comment]
@roll I added two small changes:

* Make the Show next 10 rows link less prominent, and improve the placement
* Remove the "H" cell as it was confusing. If there are only headers we don't show it, and if there are we show 1.

**Comment by roll** [comment]
@amercader
Headers could be not only on first row. And it's tabulator limitation that's headers row is unknown (long story thru post parse processors, skip rows and headers arg etc). 

Not a big thing but also could be confusing to show 1 if headers on 10 row. And other row numbers are exact as in the user file.

Anyway pretty minor so +1 with any.

**Comment by amercader** [comment]
@roll you are right. I'll just changed it to show an empty cell on this case, which I think works well on all cases. I'll merge if the tests pass.

**Pull request merged**
