### PR TITLE
Integrate design and functionality to one-column layout

### LINKED ISSUE #182: Finish Source page implementation
# Overview

We need a dedicated source page using Sam's design but with layout like beta Travis (one-column).

# General

- [x] create `/source` endpoint
- [x] add missing api endpoints if needed
- [x] update `Source` component (make it page)
- [x] correctly show errored jobs
- [x] add breadcrumbs
- [x] add time (see above report tab)
- [x] show `job number of job count` (#XX of YY)
- [x] add links to source (github/amazon)
- [x] SourceListItem should show correct job eg owner/repo/jobs/1

# Report

- [x] Only display a preview of 10 rows per error group (+ a "Only 10 rows with errors are displayed" message if necessary)

# Job History

- [x] implement job history

### LINKED ISSUE #184: Finish Home page implemenation
# Overview

See - https://smth.github.io/goodtables-ui/

# Tasks

- [ ] TBD

### LINKED ISSUE #185: Finish Settings page implementation
# Overview

Two tabs: Github / Amazon S3
- GitHub
  - A button to sync the user account (ie get all user’s repos)
  - A list of repos, with the ones active on top, and a switch to activate or deactivate them
  - Ideally the repos would be filtered by organization to help navigate them but 
- Amazon S3
  - A list of active buckets, with name, link to jobs and option to remove / deactivate
  - A form to add new buckets, with three fields: name, access key id and secret access

# Tasks

- [ ] TBD

### PR DESCRIPTION
**Pull request by roll**
- fixes #182 
- fixes #184 
- fixes #185

---

Design issues has added to #187 (I suppose the simplest way to work for Sam will be with one design issue so I mark per page issues with `fixes` keyword because it's programming-wise done).

### CODE REVIEW

**Comment by roll** [comment]
@amercader 
please take a look

**Comment by amercader** [comment]
@roll really good stuff. See my two review comments. Also I think we should try to do as much as we can on the different components ourselves to make Sam's life easier. With that in mind I think there are couple of things we can improve:

* Source header: Apart from too much green / red (added to #187), there is too much duplicated information. I don't think we should render a `SourceListItem` at all, just add the info we need from it to the `Source_` header. I would put the job number next to the source name. Source name clickable: repo name to the source page and org page to the owner page (when it's implemented, see review comment). It would be good to have git specific info (branch, commit sha, commit message), we should start storing these in the job conf, which should be easy.

    fdkejkb

* Job list: I don't like to use `SourceList` for this, there's just to much noise with the source name duplicated. I think we need `JobList` and `JobListItem` components that show only what we need. We'll probably need some of the new git info to add but we can start with the sha.

    gh7c1qm

**Comment by amercader** [comment]
@roll I think we can merge this as is and improve it later on. The settings page looks atrocious but I'm not sure if we can do more at this page to help @smth.

If you have time today could you do the necessary changes so jobs store the commit message and the branch name in their conf so we can display it in the source page / job listing?

**Comment by amercader** [comment]
And any of the issues listed in #187 that you think you can solve!

**Pull request merged**
