### PR TITLE
Use users OAuth token when interacting with the API

### LINKED ISSUE #132: Use user own token to set statuses on GitHub
We are still using a hardcoded one, which means it only works on the `frictionlessdata` organization.

Need to investigate a bit the best option for this.

### PR DESCRIPTION
**Pull request by amercader**
Fixes #132 

Rather than our hardcoded one that only works on the frictionlessdata org

This adds a new `conf ` column to the users table, and removes a lot of the model helpers that you didn't like @roll :)
Stores the oauth token in the database and not the Flask session anymore.

WIP as I still need to encrypt the tokens for security

### CODE REVIEW

**Comment by amercader** [comment]
@roll this is ready to review. I added basic functionality to encrypt the oauth tokens (and the s3 keys while I was at it)

**Comment by amercader** [comment]
All green now

**Comment by roll** [comment]
@amercader 
I'm getting on fresh system (remove-create db, migrate) after Log In - not sure what it could be: 
```
Traceback (most recent call last):
  File "/home/roll/projects/goodtables.io/.python/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/roll/projects/goodtables.io/.python/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/roll/projects/goodtables.io/.python/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/roll/projects/goodtables.io/.python/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/roll/projects/goodtables.io/.python/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/roll/projects/goodtables.io/.python/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/roll/projects/goodtables.io/.python/lib/python3.5/site-packages/flask/app.py", line 1545, in handle_user_exception
    return handler(e)
  File "/home/roll/projects/goodtables.io/goodtablesio/blueprints/api.py", line 40, in handle_api_errors
    raise error
  File "/home/roll/projects/goodtables.io/.python/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roll/projects/goodtables.io/.python/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roll/projects/goodtables.io/goodtablesio/blueprints/user.py", line 108, in authorized
    user.github_oauth_token = response['access_token']
  File "/home/roll/projects/goodtables.io/goodtablesio/integrations/github/models/user.py", line 23, in set_token
    self.conf['github_oauth_token'] = encrypt_string(value)
  File "/home/roll/projects/goodtables.io/goodtablesio/crypto.py", line 8, in encrypt_string
    f = Fernet(key)
  File "/home/roll/projects/goodtables.io/.python/lib/python3.5/site-packages/cryptography/fernet.py", line 34, in __init__
    key = base64.urlsafe_b64decode(key)
  File "/usr/lib/python3.5/base64.py", line 135, in urlsafe_b64decode
    return b64decode(s)
  File "/usr/lib/python3.5/base64.py", line 90, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

**Comment by amercader** [comment]
Are you using a valid key for `GTIO_SECRET_KEY`? You can not use just some random string it needs to be a valid base64 string. You can get one by:

```python
from cryptography.fernet import Fernet
Fernet.generate_key()
```

or just call this which is what the library does:

```python
base64.urlsafe_b64encode(os.urandom(32))
```

I'll catch this exception to provide a more meaningful error and add it to the readme.

**Comment by roll** [comment]
Thanks, except this it looks very good. I'll could be able to rerun on evening. So please merge if needed earlier.

**Pull request merged**
