### PR TITLE
Implement Dashboard based on the new design

### PR DESCRIPTION
**Pull request by amercader**

### CODE REVIEW

**Comment by amercader** [comment]
@roll this is still WIP but would be great if you could have a look and tell me what you think.

Also I could use your help on something. Basically I want to make the left hand column functional, ie when you click on job the relevant details / report is rendered on the right. I have the [handler](https://github.com/frictionlessdata/goodtables.io/pull/178/files#diff-ad64e8808dc9a089a6e084d8a05a89fcR30) on the relevant component but how do I pass the new prop ( `job`) to the relevant component (`Source_`)?

**Comment by roll** [comment]
@amercader 
I think method to solve things like this without global state (https://github.com/vuejs/vuex) is:
- Dashboard send callback prop `changeJob` to SourceList
- SourceList send callback prop `changeJob` to SourceListItem
- on click SourceListItem just call `changeJob(job)`
- in this callback function Dashboard update internal state
This callback as a prop approach is one of core approaches in systems like React/Vue/Redux etc as far as I've dived into it.

**Comment by amercader** [comment]
@roll, thanks I'll give it a go

**Comment by amercader** [comment]
@roll See d21879e for how I approached dynamically changing things when a job was selected on the left menu.

After investigating a bit I decided to go with the approach of a central event hub, as suggested by the Vue migration guide to 2.x:
    
    https://vuejs.org/v2/guide/migration.html#dispatch-and-broadcast-replaced
    
The only thing I'm not 100% happy with this approach is that I need to pass the eventHub instance as prop from Dashboard > SourceList >  SourceListItem. I think it would make sense to have a global instance for this object defined in Dashboard but I could not manage to import it / reference it from the child components (maybe it's a webpack thing). It's not too bad though, I think we can stick with for now.

**Comment by roll** [comment]
@amercader 
I suppose less global state - easier to test individual components.

**Comment by amercader** [comment]
@roll as agreed let's merge this as is. The only thing I wanted to do before merging is showing all users sources instead of the last n jobs, but this can be done on a separate PR.

**Comment by roll** [comment]
@amercader 
:+1:

**Pull request merged**
