### PR TITLE
[WIP] UI Tweaks

### PR DESCRIPTION
**Pull request by vitorbaptista**
Many fixes and tweaks for the new UI. Remaining tasks:

- [x] Review home page text
- [ ] Source's empty message flashes on load (maybe fix with `v-cloak`)
- [ ] Add spinner while enabling new repository
- [x] On the dashboard, allow multiple sections to be expanded at once (or keep them expanded by default)
- [ ] Running job has no label image (like the "cross" or "tick" for failed/successful jobs)

Some of these tasks don't need to be done now, just adding here to document.

### CODE REVIEW

**Comment by amercader** [comment]
Some more things:

* I think you already fixed that on 
1950f5f, but on Chrome most of the times the Settings page appeared like this to me:

screenshot from 2018-02-02 14-09-23

* The horizontal scrolling issue for the tables in the report should be fixed at some point, either with horizontal scrolling or just showing the affected columns. It's specially bad on mobile as there is not much space for showing table columns:

screenshot_20180130-163056

* Plus and minus signs in the Settings page should have `cursor: pointer`
* As @roll said we need to handle better long names as these tend to overlap all over the place:

2018-02-02-15-17-staging goodtables io

**Comment by roll** [comment]
@amercader 
As far as I know, @smth should be back to today to check this thing with Settings page. I've described the problem in the initial PR.

Also, I think even more things should be clickable. Based on my experience based on the work on the update - many times I was clicking on something expecting a link but it wasn't.

**Comment by smth** [comment]
Is there somewhere I can see a hosted version?

**Comment by roll** [comment]
@smth 
http://staging.goodtables.io/

**Comment by smth** [comment]
Thanks. So it looks like that issue might derive from the fact that the content of all the tabs is visible when the page first loads. Can you remove the `active` class from all but the github tab-pane?

**Comment by vitorbaptista** [comment]
FYI, the code in staging doesn't have these changes. The "Manage Sources" issue is already solved, I'll check the horizontal scrolling and the others in my TODO list.

**Comment by amercader** [comment]
I can't see the font icons anymore with the latest update:

2018-02-07-10-28-staging goodtables io

**Pull request merged**
