### PR TITLE
Major UI update

### PR DESCRIPTION
**Pull request by roll**
Known issues:
- http://staging.goodtables.io/settings uses `parts-selector` (Sam's lib). The lib itself is pretty great but for now, I have no idea how to integrate it into the Vue application. It handles actions by itself etc while the app loads repo lists from the server etc. As a solution, I think for now we just could fix the current design (in my browser it looks messed up because the `parts-selector` is not initialized I guess), make control elements clickable and after that probably add some vue/css based animations. But not sure we're able to integrate jQuery way here. 
- (Adria) We need some sort of horizontal scrolling for large tables, otherwise, you can't see all errors/fields:
https://frictionlessdata.github.io/goodtables-ui/?source=https%3A%2F%2Fgithub.com%2Famercader%2Fcar-fuel-and-emissions%2Fraw%2Fmaster%2Fdata.csv&schema=https%3A%2F%2Fgithub.com%2Famercader%2Fcar-fuel-and-emissions%2Fraw%2Fmaster%2Fschema.json&apiJobId=50e5dc4d-8094-4027-8154-d6b2c2aa3d37 (in goodtables.io context it's too wide breaking the page)
- in some places long file name/commit message could be nicely hidden using CSS I suppose (with alpha gradient)
- I think much more things should be clickable (like commit message etc)

The design is not yet created (I wasn't able to find in the mockup - correct me if I'm wrong). It uses some base looking alternative for now:
- list of warnings in the reports
- a valid table doesn't have access to processed checks so can't be shown as in mockup (for now just a label `valid table`)
- source badges
- flash messages

---

Related: https://github.com/frictionlessdata/goodtables-ui/pull/18

### CODE REVIEW

**Comment by roll** [comment]
@amercader 
Please review (also see the first post)

cc
@smth 
@vitorbaptista

**Comment by roll** [comment]
https://staging.goodtables.io

**Comment by amercader** [comment]
@roll @vitorbaptista @smth 

I think the update is great, a massive improvement from the previous version, well done @smth and @roll!

I'll add a few comments on #288

**Comment by roll** [comment]
Discussion is MOVED to https://github.com/frictionlessdata/goodtables.io/pull/288

**Pull request merged**
