### PR TITLE
[#296] Allow validation of uploaded data packages

### PR DESCRIPTION
**Pull request by vitorbaptista**
@roll @amercader There was a bug when uploading a datapackage to https://try.goodtables.io. Part was on `goodtables-ui` (fixed on https://github.com/frictionlessdata/goodtables-ui/commit/002c889480e55d78d5dfcf367cfde12b84e28b52), and other part here.

Here, the problem was that we were only validating sources with `preset == 'table'`. I changed to validate both `table` and `datapackage`, but I'm wondering what was the reason to validate only table presets. I imagine this is because a data package with local files won't be validated (or would cause some potential security issue)?

### CODE REVIEW

**Comment by roll** [comment]
@vitorbaptista 
It just wasn't implemented at all.

If you remember we were able to support data packages without local resources on `goodtables-ui` level via this hack - https://github.com/frictionlessdata/goodtables-ui/pull/19 (also not sure it was enough for https://github.com/frictionlessdata/goodtables-ui/issues/4 even for this limited scope)

But a full support for data packages with local resource could require some (serious?) work on `goodtables-js` level.

Regarding the goodtables.io level, I think initially it was only for `table` preset because internally goodtables.io doesn't need to validate data packages (cc @amercader)

**Comment by vitorbaptista** [comment]
@roll so you're saying that if I enable goodtables for a repository with a
datapackage, like https://github.com/vitorbaptista/birmingham_schools, it
won't validate the data package, but the CSV file itself? In other words,
this validation isn't using the table schema in the data package.

On 22 Feb 2018 9:11 am, "roll" <notifications@github.com> wrote:

@vitorbaptista <https://github.com/vitorbaptista>
It just wasn't implemented at all.

If you remember we were able to support data packages without local
resources on goodtables-ui level via this hack -
frictionlessdata/goodtables-ui#19
<https://github.com/frictionlessdata/goodtables-ui/pull/19> (also not sure
it was enough for frictionlessdata/goodtables-ui#4
<https://github.com/frictionlessdata/goodtables-ui/issues/4> even for this
limited scope)

But a full support for data packages with local resource could require some
(serious?) work on goodtables-js level.

Regarding the goodtables.io level, I think initially it was only for table
preset because internally goodtables.io doesn't need to validate data
packages (cc @amercader <https://github.com/amercader>)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/frictionlessdata/goodtables.io/pull/297#issuecomment-367614516>,
or mute the thread

**Comment by roll** [comment]
@vitorbaptista 
No, internally it should use a proper `datapackage` preset with a full validation. 

So I was wrong. Not sure why API doesn't support data packages then.

**Comment by roll** [comment]
One guess that it was a security issue because prior the specs v1 data packages was supporting relative paths.

**Comment by vitorbaptista** [comment]
Thanks, I'll merge this for now, and make a note to investigate and add tests on how we handle validating data packages.

**Pull request merged**
