### PR TITLE
Bootstrap frontend framework

### PR DESCRIPTION
**Pull request by roll**
- fixes [partially] #92
- this PR covers all new chore stuff on the repo

---

For a review - https://github.com/frictionlessdata/goodtables.io/tree/bootstrap-frontend

### CODE REVIEW

**Comment by roll** [comment]
@amercader 
I suppose we better rename `goodtablesio` to `backend`?

**Comment by roll** [comment]
@amercader

**Comment by roll** [comment]
@amercader 
I suppose it's ready for a review - it seems enough changes for one PR. Here I cover all new chore stuff. Next PRs could be: 
- `goodtablesio->backend` (if we will decide)
- integrate server with bundle

**Comment by amercader** [comment]
I wouldn't rename `goodtablesio` to `backend`, as we'll probably end up moving the frontend to a separate repo and it will make sense for the Python modules to keep their current names.

What's the difference with `npm run spec` and `npm run test:front` (eg frontend/tests/ and specs/)?

**Comment by roll** [comment]
@amercader 
Thanks. I will update readme - `npm run test` is unit testing for front and back and `npm run spec` is e2e testing for both

**Pull request merged**
