### PR TITLE
Fix detect all csv bug

### LINKED ISSUE #206: Failing to detect all CSVs in the repo
https://github.com/gabelula/causanatura-datos

### PR DESCRIPTION
**Pull request by roll**
- fixes #206

---

@amercader 
I can't reproduce it on unit test level (see added test) and on integration level because of #211.

### CODE REVIEW

**Comment by amercader** [comment]
@roll This was much easier that expected. Basically goodtables has a default value of 10 tables maximum per inspector :)

I've bumped that a bit and it should now detect all tables in the repo.

This made surface another bug: https://github.com/frictionlessdata/goodtables-py/issues/189 (thank you very much @gabelula, this repo is gold for testing! :rocket: ). Also related #214. 

I'm not sure where these test failures are coming from though.

**Comment by roll** [comment]
That's funny) Shame on me.

Also related to https://github.com/frictionlessdata/goodtables-py/issues/184 (why we had no idea of the real reason)

**Comment by gabelula** [comment]
Are you updating the staging.goodtables.io service soon?

**Comment by amercader** [comment]
@gabelula https://staging.goodtables.io is automatically updated every time we push to master (and tests pass). So it was last updated when this PR was merged.

**Pull request merged**
