### PR TITLE
Improved frontend building workflow

### LINKED ISSUE #144: Setup proper frontend build
# Overview

We need:
- hash for static files
- rebase on minified version for prod
- vary index.html bundle link based on dev/prod
- livereloading/hot-module-replacement for dev (not sure what's possible and what's not for now with our current hybrid setup)

### PR DESCRIPTION
**Pull request by roll**
- fixes #144

### CODE REVIEW

**Comment by roll** [comment]
@amercader 
Please take a look - it address all problems mentioned in #144. I hope it use some eloquent way to handle it) Now we even almost have livereloading to work on frontend (no auto page refresh but still there is no need to build or restart anything manually).

**Comment by amercader** [comment]
This looks really exciting! I tested and it worked as expected but can you explain a bit how does it work? eg index.min.html vs index.html

**Comment by roll** [comment]
Yes of course:
1. we have everything related to frontend in `frontend` folder including `index.html`
2. based on env var webpack builds `bundle.js` or `bundle.min.js` (with hash) into `public` folder
3. based on env var webpack builds `index.html` or `index.min.html` (using HtmlWebpackPlugin) into `public` folder injecting proper bundle.js automatically (2 and 3 happen in on run)
4. flask read static files and templates from `public` folder so index changes trigger template update (it happens without server restart like on python files change)

**Comment by amercader** [comment]
Thanks for the clear explanation, makes sense now!

**Pull request merged**
