### PR TITLE
Implemented simple job view

### LINKED ISSUE #7: Basic, functional UI to see reports [1.5d]
# Description

Very minimal design. Just a simple Bootstrap UI, showing the report for a given run.

For the MVP, this probably means:

- user clicks button/action on GitHub UI (from a pull request)
- that goes to a page, which pulls in the report from the static storage, and renders it in the UI

Lots more can be done later! We don't need much more than the above for the MVP.

# Tasks

- [x] Create an endpoint that renders a report template from the JSON report stored in S3

# Estimate

2

### PR DESCRIPTION
**Pull request by roll**
- fixes #7 
- fixes [partially] #24 (renamed table `reports` to `jobs`)

---

For job triggered by https://github.com/roll/goodtables-example repository:

> Get /job/78be4c2c-3dad-4816-937a-2a2d1feb61ff

localhost 5000 job 78be4c2c 3dad 4816 937a 2a2d1feb61ff

### CODE REVIEW

**Comment by roll** [comment]
@amercader 
please take a look

**Comment by amercader** [comment]
@roll What is Dataset?

**Comment by roll** [comment]
@amercader 
https://github.com/frictionlessdata/goodtables-py#dataset

**Comment by amercader** [comment]
I see. I seems a bit confusing to me. Maybe we can merge the information in Dataset with Overview as conceptually it seems to fit well together.

**Comment by roll** [comment]
I'm creating issue for it - some other improvements needed also.

**Pull request merged**
